name: aula_18_09_2023
description: A new Flutter project.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+5
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.3  
  permission_handler: ^10.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
